### ISSUE TITLE
Output filename not configured.

### ISSUE THREAD

**Issue by cafe4it** [Dharmoslap/redux-chrome-extension#3]
Hi, i got error : npm start 

```
 npm start 

> redux-chrome-extension@1.1.0 start /D/Projects/chrome-ext/chatchatchit
> webpack --watch

webpack 1.13.1
Usage: https://webpack.github.io/docs/cli.html

Options:
  --help, -h, -?                                                                                  
  --config                                                                                        
  --context                                                                                       
  --entry                                                                                         
  --module-bind                                                                                   
  --module-bind-post                                                                              
  --module-bind-pre                                                                               
  --output-path                                                                                   
  --output-file                                                                                   
  --output-chunk-file                                                                             
  --output-named-chunk-file                                                                       
  --output-source-map-file                                                                        
  --output-public-path                                                                            
  --output-jsonp-function                                                                         
  --output-pathinfo                                                                               
  --output-library                                                                                
  --output-library-target                                                                         
  --records-input-path                                                                            
  --records-output-path                                                                           
  --records-path                                                                                  
  --define                                                                                        
  --target                                                                                        
  --cache                                                                                           [default: true]
  --watch, -w                                                                                     
  --watch which closes when stdin ends                                                            
  --watch-aggregate-timeout                                                                       
  --watch-poll                                                                                    
  --hot                                                                                           
  --debug                                                                                         
  --devtool                                                                                       
  --progress                                                                                      
  --resolve-alias                                                                                 
  --resolve-loader-alias                                                                          
  --optimize-max-chunks                                                                           
  --optimize-min-chunk-size                                                                       
  --optimize-minimize                                                                             
  --optimize-occurence-order                                                                      
  --optimize-dedupe                                                                               
  --prefetch                                                                                      
  --provide                                                                                       
  --labeled-modules                                                                               
  --plugin                                                                                        
  --bail                                                                                          
  --profile                                                                                       
  -d                                    shortcut for --debug --devtool sourcemap --output-pathinfo
  -p                                    shortcut for --optimize-minimize                          
  --json, -j                                                                                      
  --colors, -c                                                                                    
  --sort-modules-by                                                                               
  --sort-chunks-by                                                                                
  --sort-assets-by                                                                                
  --hide-modules                                                                                  
  --display-exclude                                                                               
  --display-modules                                                                               
  --display-chunks                                                                                
  --display-error-details                                                                         
  --display-origins                                                                               
  --display-cached                                                                                
  --display-cached-assets                                                                         
  --display-reasons, --verbose, -v                                                                

Output filename not configured.

npm ERR! Linux 3.19.0-64-generic
npm ERR! argv "/home/nxcong/.nvm/versions/node/v6.2.1/bin/node" "/home/nxcong/.nvm/versions/node/v6.2.1/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! redux-chrome-extension@1.1.0 start: `webpack --watch`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the redux-chrome-extension@1.1.0 start script 'webpack --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-chrome-extension package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-chrome-extension
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-chrome-extension
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /D/Projects/chrome-ext/chatchatchit/npm-debug.log

```

**Comment by ogavrushev** [comment]
try webpack --config webpack.config.dev.js --watch

**Comment by cafe4it** [comment]
@ogavrushev Thanks.

```
Hash: 891865a043ec64884cdb
Version: webpack 1.13.1
Time: 696ms
   [0] multi options 40 bytes {0} [built] [1 error]
   [0] multi popup 40 bytes {1} [built] [1 error]
    + 16 hidden modules

ERROR in ./src/scripts/popup.js
Module build failed: Error: Cannot find module './lib/babel'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/react-hot-loader/babel.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:202:20
    at Array.map (native)
    at Function.normalisePlugins (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-loader/index.js:88:12)
 @ multi popup

ERROR in ./src/scripts/options.js
Module build failed: Error: Cannot find module './lib/babel'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/react-hot-loader/babel.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:202:20
    at Array.map (native)
    at Function.normalisePlugins (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/nxcong/Projects/chrome-ext/chatchatchit/node_modules/babel-loader/index.js:88:12)
 @ multi options
```

**Comment by mikeon** [comment]
The same issue here.

**Comment by mikeon** [comment]
Someone have found solution on that?

**Comment by clarabridges** [comment]
@mikeon rename the dev webpack config file to webpack.config.js **or** modify package.json's start script line to pass the dev config file as it is currently named by adding --config webpack.config.dev.js  **or** add this in the array of scripts and use npm run dev instead of npm start:
`"dev": "webpack --watch --config webpack.config.dev.js"`
