### ISSUE TITLE
Cannot find module './lib/babel'

### ISSUE THREAD

**Issue by hmgibson23** [Dharmoslap/redux-chrome-extension#4]
I get this when I run it:

```
ERROR in ./src/scripts/popup.js
Module build failed: Error: Cannot find module './lib/babel'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hugo/redux-chrome-extension/node_modules/react-hot-loader/babel.js:1:80)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:202:20
    at Array.map (native)
    at Function.normalisePlugins (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/hugo/redux-chrome-extension/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/home/hugo/redux-chrome-extension/node_modules/babel-loader/lib/index.js:133:12)
 @ multi popup

ERROR in ./src/scripts/options.js
Module build failed: Error: Cannot find module './lib/babel'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hugo/redux-chrome-extension/node_modules/react-hot-loader/babel.js:1:80)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:202:20
    at Array.map (native)
    at Function.normalisePlugins (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/hugo/redux-chrome-extension/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/hugo/redux-chrome-extension/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/home/hugo/redux-chrome-extension/node_modules/babel-loader/lib/index.js:133:12)
 @ multi options

```

**Comment by hmgibson23** [comment]
Any help would be appreciated.
